InfoSec-Agent/InfoSec-Agent

cryptography/cryptography.go, cryptography/cryptography_test.go, go.mod, go.sum
For encrypting / decrypting strings
=> Cryptography package

localization/localizations_src/de/active.de.json, localization/localizations_src/en-GB/active.en-GB.json, localization/localizations_src/en-US/active.en-US.json, localization/localizations_src/es/active.es.json, localization/localizations_src/fr/active.fr.json, localization/localizations_src/nl/active.nl.json, localization/localizations_src/pt/active.pt.json, localization/localize.go, tray/tray.go, tray/tray_test.go
Added a function in the localization package that takes the language and MessageID (that refers to the JSON key) to be localized and internally in the package localizes it instead of having the tray package do the localization.
=> Simplified and streamlined localization

localization/localizations_src/de/active.de.json, localization/localizations_src/en-GB/active.en-GB.json, localization/localizations_src/en-US/active.en-US.json, localization/localizations_src/es/active.es.json, localization/localizations_src/fr/active.fr.json, localization/localizations_src/nl/active.nl.json, localization/localizations_src/pt/active.pt.json, tray/tray.go
Sets up the system tray framework for future integration with the Wails application.
=> Reporting page integration setup

checks/bluetooth.go, checks/checks.go, checks/externaldevices.go, checks/guestaccount_check.go, checks/networksharing_check.go, checks/password_manager.go, checks/permission.go, checks/ports.go, checks/remote_desktop_check.go, checks/smb_check.go, checks/uac_check.go, checks/windows_defender.go, checks/windows_lastpasswordchange.go, checks/windows_loginmethod.go, checks/windows_outdated.go, checks/windows_secureboot.go, checks/windows_startup.go, scan/scan.go
Comments, package descriptions and general clean-up
=> Security checks documentation

main.go, scan/scan.go, tray/tray.go
scan.Scan() can be called from the tray menu. Also displays a progress dialog window with the currently running check and a progress bar.
=> Scan call from the tray application

checks/browsers/chromium/extensions_chromium.go, checks/browsers/chromium/history_chromium.go, checks/browsers/firefox/cookies_firefox.go, checks/browsers/firefox/extensions_firefox.go, checks/browsers/firefox/history_firefox.go, checks/browsers/firefox/password_firefox.go, cryptography/cryptography.go, cryptography/cryptography_test.go, icon/iconwin.go, localization/localize.go, main.go, reporting-page/app.go, reporting-page/main.go, reporting-page/tray_functions.go, tray/tray.go, tray/tray_test.go, utils/utils.go
Documentation for reporting page, security/privacy checks, and reporting page go files
=> More complete/correct documentation

checks/bluetooth.go, checks/browsers/chromium/history_chromium.go, checks/browsers/firefox/cookies_firefox.go, checks/browsers/firefox/history_firefox.go, checks/browsers/firefox/password_firefox.go, checks/externaldevices.go, checks/guestaccount_check.go, checks/networksharing_check.go, checks/password_manager.go, checks/permission.go, checks/ports.go, checks/remote_desktop_check.go, checks/smb_check.go, checks/uac_check.go, checks/windows_defender.go, checks/windows_lastpasswordchange.go, checks/windows_loginmethod.go, checks/windows_outdated.go, checks/windows_secureboot.go, checks/windows_startup.go, cryptography/cryptography_test.go, icon/iconwin.go, reporting-page/app.go, reporting-page/tray_functions.go, tray/tray_test.go
Removed redundant package descriptions so each package has only 1 file with the description.
=> Redundant package descriptions

checks/windows_outdated.go, checks/windows_outdated_test.go, scan/scan.go, windowsmock/windowsmock.go
Also adds windows version mocking
=> Unit tests for windows_outdated check

checks/externaldevices_test.go
Checks for expected cmd output
=> Integration test for externaldevices check

checks/remote_desktop_check_test.go, checks/windows_loginmethod_test.go
Now only checks values that are non-unique per user
=> Fixed KeyInfo checks

checks/remote_desktop_check_test.go, checks/windows_loginmethod_test.go
Run the (new) tests before approving this request, just to make sure it works on other devices
=> Refactor of keyinfo checks

.gitignore, reporting-page/app.go, reporting-page/frontend/wailsjs/go/models.ts, reporting-page/main.go, tray/tray.go, tray/tray_test.go, usersettings/usersettings.go
User settings are stored within the usersettings.json file, located in the usersettings folder. Used for persistent settings across sessions.
=> User settings package for language and scan interval values

reporting-page/frontend/src/css/issues.css, reporting-page/frontend/src/js/issue.js
Made it better looking and improved responsiveness
=> V24A-383 improved issue page layout

reporting-page/frontend/index.html, reporting-page/frontend/src/css/integration.css, reporting-page/frontend/src/js/integration.js, tray/tray.go
Added integration page for the Lighthouse API
=> V24 a 142 integration page

checks/smb_check.go, checks/smb_check_test.go, scan/scan.go
Improved speed of SMB check by only using one powershell session. Also updated the tests because of this change
=> V24 a 380 improve smb check

checks/browsers/browserutils/browser_utils.go, checks/browsers/firefox/history_firefox_test.go
The test can no longer fail if the database ends up being empty.
=> V24A-488 failsafe for phishingdb test

backend/checks/devices/bluetooth.go, backend/checks/windows/permission.go
Simple remove of defer inside of a separate func
=> V24A-500 Fix registry keys not opening/reading value

reporting-page/frontend/src/database.json, reporting-page/frontend/src/js/issue.js
Incorrect settings are grouped per registry key and shown in a table.
=> V24A-451 Show CIS Audit list check results on front-end

reporting-page/frontend/src/database.json, reporting-page/frontend/src/js/issue.js
Checks like bluetooth and external devices now list their results as bullet lists. Ports now displays its results in a table.
=> V24A-514 Display results as table/bullet list

backend/checks/windows/permission.go
Minor change in the permission check to fix the bug with the contacts permissions
=> fixed contact permission bug

backend/mocking/command.go, backend/scan/scan.go, backend/tray/tray.go
Console windows are now hidden and won't show up during execution of the program.
=> V24A-522 Fix windows console windows opening

reporting-page/frontend/package.json
added --no-warnings=ExperimentalWarning to node
=> Turned off experimental warnings on frontend tests

backend/integration_testing/scan_integration.go, backend/scan/scan.go, backend/scan/scan_list.go, backend/scan/scan_test.go
Scan list is now split up into multiple smaller sub-lists. Also added functionality to check if the different browsers (Chrome, Edge, Firefox) are installed and if they are, their checks are added to the scan list.
=> V24A-573 Split up of scan list

backend/checks/browsers/chromium/history.go, backend/checks/browsers/utils.go, backend/integration_testing/scan_integration.go, backend/scan/scan.go, backend/scan/scan_list.go
Scan now uses a concurrent queue to run all checks, significantly improving execution time.
=> V24A-574 Run scan concurrently

backend/integration_testing/tray_integration.go, backend/scan/scan.go, backend/scan/scan_test.go, backend/tray/tray.go, backend/tray/tray_test.go, reporting-page/frontend/src/js/database.js, reporting-page/frontend/src/js/home.js, reporting-page/frontend/src/js/privacy-dashboard.js, reporting-page/frontend/src/js/security-dashboard.js, reporting-page/frontend/test/database.test.js, reporting-page/frontend/wailsjs/go/main/Tray.d.ts, reporting-page/frontend/wailsjs/go/main/Tray.js, reporting-page/frontend/wailsjs/go/models.ts, reporting-page/tray_functions.go
Can now pass nil to Scan / false to ScanNow to not let a dialog show up when running the scan.
=> V24A-552 Scan dialog optional

backend/database/database.go, backend/database/database_test.go, backend/integration_testing/scan_integration.go, backend/scan/scan_test.go, backend/tray/tray.go, reporting-page/database_functions.go, reporting-page/main.go
More organized by having a separate database folder instead of being in the scan folder . 
Furthermore changed "DataBase" to "Database" , and for example "GetDataBaseData" to "GetData" .
=> Database name and directory change

backend/tray/tray.go, backend/tray/tray_test.go
Confirmation dialogs now appear when the scan interval gets changed by the user. Both cases of valid and invalid input have their own respective dialog.
=> V24A-589 Dialogs for scan interval change

backend/checks/devices/external_devices.go, backend/tray/tray_test.go
Now allows command output to be empty
=> V24A-613 External devices no devices found

backend/checks/utils.go, backend/checks/utils_test.go, backend/checks/windows/startup_test.go
Also adds slighly more line coverage
=> V24A-605 Startup check fix

backend/localization/localizations_src/de/active.de.json, backend/localization/localizations_src/en-GB/active.en-GB.json, backend/localization/localizations_src/en-US/active.en-US.json, backend/localization/localizations_src/es/active.es.json, backend/localization/localizations_src/fr/active.fr.json, backend/localization/localizations_src/nl/active.nl.json, backend/localization/localizations_src/pt/active.pt.json, backend/system_testing/system_test.go, backend/tray/tray.go, backend/tray/tray_test.go, backend/usersettings/user_settings.go
Default interval now set to 1 week (7 days)
=> V24A-691 Change scan interval to days

backend/checks/windows/permission.go, backend/checks/windows/permission_test.go, backend/tray/tray_test.go
Now checks the general "Allow/Deny" setting for specific permissions. Check now returns the correct values.
=> V24A-604 Permission check general on/off setting

backend/checks/cisregistrysettings/cis_registry_policies_HKLM.go, backend/checks/utils.go, backend/checks/utils_test.go, backend/checks/windows/startup.go, backend/checks/windows/startup_test.go, backend/mocking/file.go, reporting-page/tray_functions.go
2 TODO's still exist in the scan.go file. These are related to the API connection.
=> V24A-694 Complete TODO's

reporting-page/frontend/src/css/issues.css, reporting-page/frontend/src/js/issue.js
Changed the hover-magnify image to a click-to-magnify image
=> Fixed magnifying glass on click

backend/checks/windows/startup.go, backend/checks/windows/startup_test.go
Add lm2values back and removed check for non-zero first value
=> V24A-738 Fix check
